{
  "success": false,
  "error": "Traceback (most recent call last):\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 501, in _run_solc\n    ret: Dict = json.loads(stdout)\n  File \"/usr/lib/python3.8/json/__init__.py\", line 357, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.8/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.8/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/USCHunt/PycharmProjects/slither/slither/__main__.py\", line 741, in main_impl\n    ) = process_all(filename, args, detector_classes, printer_classes)\n  File \"/home/USCHunt/PycharmProjects/slither/slither/__main__.py\", line 72, in process_all\n    compilations = compile_all(target, **vars(args))\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 628, in compile_all\n    compilations.append(CryticCompile(target, **kwargs))\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 116, in __init__\n    self._compile(**kwargs)\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py\", line 539, in _compile\n    self._platform.compile(self, **kwargs)\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 149, in compile\n    targets_json = _get_targets_json(compilation_unit, self._target, **kwargs)\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 271, in _get_targets_json\n    return _run_solc(\n  File \"/home/USCHunt/PycharmProjects/slither/venv/lib/python3.8/site-packages/crytic_compile/platform/solc.py\", line 505, in _run_solc\n    raise InvalidCompilation(f\"Invalid solc compilation {stderr}\")\ncrytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /home/USCHunt/Documents/ethereum/smart-contract-sanctuary/ethereum/contracts/mainnet/proxies_and_implementations//0.5.8/6b./ethereum/contracts/mainnet/6b/6B4F20B2259Eebb97945b6EF549a1c44FcA6Cd81_Unitroller.sol/6B4F20B2259Eebb97945b6EF549a1c44FcA6Cd81_Unitroller.sol:3418:31: Error: Function not found.\n        assembly { chainId := chainid() }\r\n                              ^-----^\n/home/USCHunt/Documents/ethereum/smart-contract-sanctuary/ethereum/contracts/mainnet/proxies_and_implementations//0.5.8/6b./ethereum/contracts/mainnet/6b/6B4F20B2259Eebb97945b6EF549a1c44FcA6Cd81_Unitroller.sol/6B4F20B2259Eebb97945b6EF549a1c44FcA6Cd81_Unitroller.sol:3418:20: Error: Variable count does not match number of values (1 vs. 0)\n        assembly { chainId := chainid() }\r\n                   ^------------------^\n\n",
  "results": {}
}